### ISSUE TITLE
New page: Why Use Samvera

### ISSUE THREAD

**Issue by heathergreerklein** [samvera/samvera.org#55]
Create a new page called "why Use Samvera" using the "[grid with offset icons](https://tailwindui.com/components/marketing/sections/feature-sections#component-cdca7eda27bdaceb45026dca4c17efe7)" template in Tailwind CSS. 

This page can incorporate content from and eliminate the following pages: 
https://samvera.org/why-use-samvera/samvera-flexible-extensible
https://samvera.org/why-use-samvera/sustainability
https://samvera.org/why-use-samvera/the-samvera-community

**Comment by adamjarling** [comment]
@heathergreerklein I'd suggest we just keep a generic page layout for the new "Why Use Samvera" page, instead of using the "Grid with offset icons" template.   My thoughts are:

- There's a fair amount of content in each page, and it might overwhelm the Grid Cards in the suggested layout, making things appear lopsided in different responsive viewports.
- If we keep it on a general page, then updating will stay in Markdown, and someone doesn't have to dig through code to update the page.

Let me know your thoughts?
